import dotenv from 'dotenv';
import pg from 'pg';

dotenv.config();

const img = (seed) => `https://images.unsplash.com/${seed}?auto=format&fit=crop&w=800&q=80`;

const newPets = [
  {
    name: 'Luna',
    species: 'dog',
    breed: 'Aspin',
    birthdate: '2023-05-10',
    age_group: 'young',
    size: 'medium',
    gender: 'female',
    temperament: ['Sweet', 'Friendly', 'Energetic'],
    visibility: 'public',
    description: 'Luna is a rescue Aspin with a golden heart. She loves long walks and playdates.',
    medical_history: ['Fully Vaccinated', 'Dewormed'],
    behavioral_notes: 'Very friendly with children and other dogs.',
    status: 'In Process',
    image_url: img('photo-1543466835-00a7907e9de1'),
    gallery: [img('photo-1543466835-00a7907e9de1')],
    vaccinated: true,
    spayed_neutered: true,
    good_with_kids: true,
    good_with_pets: true,
  },
  {
    name: 'Milo',
    species: 'cat',
    breed: 'Puspin',
    birthdate: '2024-01-15',
    age_group: 'young',
    size: 'small',
    gender: 'male',
    temperament: ['Playful', 'Curious', 'Affectionate'],
    visibility: 'public',
    description: 'Milo is a vibrant Puspin kitty who loves feather toys and sunbathing.',
    medical_history: ['Vaccinated', 'Flea Treated'],
    behavioral_notes: 'Litter trained and very playful.',
    status: 'In Process',
    image_url: img('photo-1514888286974-6c03e2ca1dba'),
    gallery: [img('photo-1514888286974-6c03e2ca1dba')],
    vaccinated: true,
    spayed_neutered: true,
    good_with_kids: true,
    good_with_pets: true,
  },
  {
    name: 'Bruno',
    species: 'dog',
    breed: 'Shih Tzu Mix',
    birthdate: '2022-11-20',
    age_group: 'adult',
    size: 'small',
    gender: 'male',
    temperament: ['Gentle', 'Quiet', 'Cuddly'],
    visibility: 'public',
    description: 'Bruno is a calm and affectionate fluffball who loves lap cuddles.',
    medical_history: ['Fully Vaccinated', 'Neutered'],
    behavioral_notes: 'Great apartment dog, low energy.',
    status: 'In Process',
    image_url: img('photo-1583511655857-d19b40a7a54e'),
    gallery: [img('photo-1583511655857-d19b40a7a54e')],
    vaccinated: true,
    spayed_neutered: true,
    good_with_kids: true,
    good_with_pets: true,
  },
  {
    name: 'Bella',
    species: 'cat',
    breed: 'Siamese Mix',
    birthdate: '2023-09-01',
    age_group: 'young',
    size: 'small',
    gender: 'female',
    temperament: ['Vocal', 'Intelligent', 'Loving'],
    visibility: 'public',
    description: 'Bella is a talkative Siamese mix who will keep you company all day long.',
    medical_history: ['Vaccinated', 'Spayed'],
    behavioral_notes: 'Enjoys human company and window watching.',
    status: 'In Process',
    image_url: img('photo-1573865526739-10659fec78a5'),
    gallery: [img('photo-1573865526739-10659fec78a5')],
    vaccinated: true,
    spayed_neutered: true,
    good_with_kids: true,
    good_with_pets: false,
  },
  {
    name: 'Charlie',
    species: 'dog',
    breed: 'Golden Retriever Mix',
    birthdate: '2021-04-12',
    age_group: 'adult',
    size: 'large',
    gender: 'male',
    temperament: ['Loyal', 'Friendly', 'Smart'],
    visibility: 'public',
    description: 'Charlie is a gentle giant who excels at obedience and loves water play.',
    medical_history: ['Fully Vaccinated', 'Microchipped'],
    behavioral_notes: 'House-trained and leash-trained.',
    status: 'In Process',
    image_url: img('photo-1552053831-71594a27632d'),
    gallery: [img('photo-1552053831-71594a27632d')],
    vaccinated: true,
    spayed_neutered: true,
    good_with_kids: true,
    good_with_pets: true,
  },
  {
    name: 'Daisy',
    species: 'dog',
    breed: 'Beagle Mix',
    birthdate: '2024-06-01',
    age_group: 'puppy-kitten',
    size: 'small',
    gender: 'female',
    temperament: ['Playful', 'Curious', 'Happy'],
    visibility: 'public',
    description: 'Daisy is an adorable puppy with endless enthusiasm for exploring.',
    medical_history: ['Initial Vaccines Done', 'Dewormed'],
    behavioral_notes: 'Puppy training in progress.',
    status: 'In Process',
    image_url: img('photo-1537151608828-ea2b11777ee8'),
    gallery: [img('photo-1537151608828-ea2b11777ee8')],
    vaccinated: true,
    spayed_neutered: false,
    good_with_kids: true,
    good_with_pets: true,
  },
  {
    name: 'Oliver',
    species: 'cat',
    breed: 'Persian Mix',
    birthdate: '2022-03-18',
    age_group: 'adult',
    size: 'small',
    gender: 'male',
    temperament: ['Calm', 'Mellow', 'Sweet'],
    visibility: 'public',
    description: 'Oliver has soft fur and a peaceful personality. Perfect indoor companion.',
    medical_history: ['Fully Vaccinated', 'Neutered'],
    behavioral_notes: 'Very quiet, loves grooming.',
    status: 'In Process',
    image_url: img('photo-1533738363-b7f9aef128ce'),
    gallery: [img('photo-1533738363-b7f9aef128ce')],
    vaccinated: true,
    spayed_neutered: true,
    good_with_kids: true,
    good_with_pets: true,
  },
  {
    name: 'Coco',
    species: 'dog',
    breed: 'Labrador Mix',
    birthdate: '2023-02-14',
    age_group: 'young',
    size: 'large',
    gender: 'female',
    temperament: ['Active', 'Social', 'Affectionate'],
    visibility: 'public',
    description: 'Coco is an active girl who loves running, fetch, and belly rubs.',
    medical_history: ['Fully Vaccinated', 'Spayed'],
    behavioral_notes: 'High energy, great running buddy.',
    status: 'In Process',
    image_url: img('photo-1587300003388-59208cc962cb'),
    gallery: [img('photo-1587300003388-59208cc962cb')],
    vaccinated: true,
    spayed_neutered: true,
    good_with_kids: true,
    good_with_pets: true,
  },
  {
    name: 'Teddy',
    species: 'rabbit',
    breed: 'Netherland Dwarf',
    birthdate: '2024-03-25',
    age_group: 'young',
    size: 'small',
    gender: 'male',
    temperament: ['Gentle', 'Timid', 'Sweet'],
    visibility: 'public',
    description: 'Teddy is a cute bunny who loves fresh greens and gentle petting.',
    medical_history: ['Health checked', 'Dewormed'],
    behavioral_notes: 'Litter box trained.',
    status: 'In Process',
    image_url: img('photo-1585110396000-c9ffd4e4b308'),
    gallery: [img('photo-1585110396000-c9ffd4e4b308')],
    vaccinated: true,
    spayed_neutered: false,
    good_with_kids: true,
    good_with_pets: true,
  },
  {
    name: 'Loki',
    species: 'dog',
    breed: 'Husky Mix',
    birthdate: '2022-08-05',
    age_group: 'adult',
    size: 'large',
    gender: 'male',
    temperament: ['Playful', 'Vocal', 'Adventurous'],
    visibility: 'public',
    description: 'Loki has striking eyes and a majestic coat. Needs an active home.',
    medical_history: ['Fully Vaccinated', 'Neutered'],
    behavioral_notes: 'Loves outdoors and active exercise.',
    status: 'In Process',
    image_url: img('photo-1605568427561-40dd23c2acea'),
    gallery: [img('photo-1605568427561-40dd23c2acea')],
    vaccinated: true,
    spayed_neutered: true,
    good_with_kids: true,
    good_with_pets: true,
  },
  {
    name: 'Cleo',
    species: 'cat',
    breed: 'Domestic Short Hair',
    birthdate: '2023-12-10',
    age_group: 'young',
    size: 'small',
    gender: 'female',
    temperament: ['Independent', 'Playful', 'Friendly'],
    visibility: 'public',
    description: 'Cleo is a stylish tabico cat who loves perch towers and laser toys.',
    medical_history: ['Vaccinated', 'Spayed'],
    behavioral_notes: 'Independent but cuddly on her terms.',
    status: 'In Process',
    image_url: img('photo-1526336024174-e58f5cdd8e13'),
    gallery: [img('photo-1526336024174-e58f5cdd8e13')],
    vaccinated: true,
    spayed_neutered: true,
    good_with_kids: true,
    good_with_pets: true,
  },
  {
    name: 'Buster',
    species: 'dog',
    breed: 'Aspin',
    birthdate: '2020-07-22',
    age_group: 'senior',
    size: 'medium',
    gender: 'male',
    temperament: ['Calm', 'Loyal', 'Gentle'],
    visibility: 'public',
    description: 'Buster is a gentle senior dog who wants nothing more than a warm cozy bed.',
    medical_history: ['Senior Bloodwork Clear', 'Vaccinated'],
    behavioral_notes: 'Low energy, quiet, house-trained.',
    status: 'In Process',
    image_url: img('photo-1517849845537-4d257902454a'),
    gallery: [img('photo-1517849845537-4d257902454a')],
    vaccinated: true,
    spayed_neutered: true,
    good_with_kids: true,
    good_with_pets: true,
  },
  {
    name: 'Nala',
    species: 'dog',
    breed: 'German Shepherd Mix',
    birthdate: '2023-10-30',
    age_group: 'young',
    size: 'large',
    gender: 'female',
    temperament: ['Protective', 'Smart', 'Attentive'],
    visibility: 'public',
    description: 'Nala is eager to please and very quick at learning new commands.',
    medical_history: ['Fully Vaccinated', 'Spayed'],
    behavioral_notes: 'Obedience trained.',
    status: 'In Process',
    image_url: img('photo-1589941013453-ec89f33b5e95'),
    gallery: [img('photo-1589941013453-ec89f33b5e95')],
    vaccinated: true,
    spayed_neutered: true,
    good_with_kids: true,
    good_with_pets: true,
  },
  {
    name: 'Mochi',
    species: 'cat',
    breed: 'Puspin',
    birthdate: '2024-05-02',
    age_group: 'puppy-kitten',
    size: 'small',
    gender: 'female',
    temperament: ['Sweet', 'Playful', 'Tiny'],
    visibility: 'public',
    description: 'Mochi is a sweet little kitten who purrs the moment you touch her.',
    medical_history: ['Dewormed', 'Kitten Shots Started'],
    behavioral_notes: 'Very affectionate.',
    status: 'In Process',
    image_url: img('photo-1561948955-570b270e7c36'),
    gallery: [img('photo-1561948955-570b270e7c36')],
    vaccinated: true,
    spayed_neutered: false,
    good_with_kids: true,
    good_with_pets: true,
  },
  {
    name: 'Simba',
    species: 'dog',
    breed: 'Chihuahua Mix',
    birthdate: '2021-09-15',
    age_group: 'adult',
    size: 'small',
    gender: 'male',
    temperament: ['Bold', 'Loving', 'Alert'],
    visibility: 'public',
    description: 'Simba has a big personality in a tiny body. Loves carrying his squeaky toy.',
    medical_history: ['Vaccinated', 'Neutered'],
    behavioral_notes: 'Loves lap napping.',
    status: 'In Process',
    image_url: img('photo-1518717758536-85ae29035b6d'),
    gallery: [img('photo-1518717758536-85ae29035b6d')],
    vaccinated: true,
    spayed_neutered: true,
    good_with_kids: true,
    good_with_pets: true,
  },
];

const seedPets = async () => {
  const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
  try {
    const shelterRes = await pool.query(
      "SELECT id, name FROM shelters WHERE name ILIKE '%Happy Rescue Shelter%'"
    );

    if (shelterRes.rows.length === 0) {
      throw new Error('Happy Rescue Shelter not found in database!');
    }

    const shelterId = shelterRes.rows[0].id;
    console.log(`Found shelter: ${shelterRes.rows[0].name} (${shelterId})`);

    let count = 0;
    for (const p of newPets) {
      await pool.query(
        `INSERT INTO pets (name, species, breed, birthdate, age_group, size, gender, temperament,
          shelter_id, visibility, description, medical_history, behavioral_notes, status,
          image_url, gallery, vaccinated, spayed_neutered, good_with_kids, good_with_pets)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20)`,
        [
          p.name, p.species, p.breed, p.birthdate, p.age_group, p.size, p.gender, p.temperament,
          shelterId, p.visibility, p.description, p.medical_history, p.behavioral_notes, p.status,
          p.image_url, p.gallery, p.vaccinated, p.spayed_neutered, p.good_with_kids, p.good_with_pets,
        ],
      );
      count++;
    }

    console.log(`Successfully seeded ${count} pending pets for ${shelterRes.rows[0].name}.`);
  } catch (err) {
    console.error('Error seeding pets:', err);
  } finally {
    await pool.end();
  }
};

seedPets();
